name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        php: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0' ]

    name: PHP ${{ matrix.php }} test

    steps:
    - uses: actions/checkout@master

    - name: Setup PHP ${{ matrix.php }}
      uses: nanasess/setup-php@master
      with:
        php-version: ${{ matrix.php }}

    - name: Print php version
      run: php --version

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: composer run-script test

    - name: Run static analysis
      run: composer run-script analyze
